import type { DataTableColumn, DataTableRow } from "./DataTable.types";

export const DEMO_TABLE_COLUMNS: DataTableColumn[] = [
  { id: "holeNumber", label: "Hole Number" },
  { id: "from", label: "From" },
  { id: "to", label: "To" },
  { id: "length", label: "Length" },
  { id: "rcDd", label: "RC/DD" },
  { id: "lithoDomain", label: "Litho_Domain" },
  { id: "legacyCode", label: "Legacy_Code" },
  { id: "minDiagnostic", label: "Min_Diagnostic" },
  { id: "oxidation", label: "Oxidation" },
  { id: "sampleType", label: "Sample_Type" },
  { id: "assayAu", label: "Assay_Au" },
  { id: "assayCu", label: "Assay_Cu" },
  { id: "recoveryPct", label: "Recovery_Pct" },
  { id: "alteration", label: "Alteration" },
  { id: "geologist", label: "Geologist" },
  { id: "dateLogged", label: "Date_Logged" },
  { id: "structureCode", label: "Structure_Code" },
];

const FIGMA_REPEAT_ROW = {
  holeNumber: "RJ220",
  from: "107.0",
  to: "120.0",
  length: "13.222",
  rcDd: "",
  lithoDomain: "PP",
  legacyCode: "Zanco",
  minDiagnostic: "OIC",
  oxidation: "",
  sampleType: "Core",
  assayAu: "0.42",
  assayCu: "0.18",
  recoveryPct: "96.5",
  alteration: "Silicic",
  geologist: "J. Rivera",
  dateLogged: "2024-03-14",
  structureCode: "F1-NE",
} as const;

function createRepeatRow(index: number): DataTableRow {
  return {
    id: `row-${index}`,
    cells: { ...FIGMA_REPEAT_ROW },
  };
}

export const DEMO_TABLE_ROWS: DataTableRow[] = [
  {
    id: "row-1",
    cells: {
      holeNumber: "RJ220",
      from: "48.0",
      to: "96.0",
      length: "48.0",
      rcDd: "",
      lithoDomain: {
        value: "PP",
        status: "approved",
        panelState: "approved",
        invalidValue: "PP",
        cellCount: 1,
        holeCount: 1,
        initialStagedValue: "bnd",
      },
      legacyCode: "Zqsmu",
      minDiagnostic: "OIC",
      oxidation: "Oxidized",
      sampleType: "Core",
      assayAu: "1.24",
      assayCu: "0.31",
      recoveryPct: "98.2",
      alteration: "Argillic",
      geologist: "M. Chen",
      dateLogged: "2024-02-18",
      structureCode: "F2-NW",
    },
  },
  {
    id: "row-2",
    cells: {
      holeNumber: "RJ220",
      from: "100.0",
      to: "105.0",
      length: "5.0",
      rcDd: "",
      lithoDomain: {
        value: "PP",
        status: "staged",
        panelState: "staged",
        invalidValue: "PP",
        cellCount: 2,
        holeCount: 1,
        initialStagedValue: "lst-a",
      },
      legacyCode: "Zqsmu",
      minDiagnostic: "OIC",
      oxidation: "",
      sampleType: "Chip",
      assayAu: "0.87",
      assayCu: "0.22",
      recoveryPct: {
        value: "badpct",
        status: "staged",
        panelState: "staged",
        invalidValue: "badpct",
        cellCount: 2,
        holeCount: 1,
        initialStagedValue: "lst-b",
      },
      alteration: "Phyllic",
      geologist: "A. Okonkwo",
      dateLogged: "2024-02-22",
      structureCode: "F1-NE",
    },
  },
  {
    id: "row-3",
    cells: {
      holeNumber: "RJ220",
      from: "105.0",
      to: "110.0",
      length: "5.0",
      rcDd: "",
      lithoDomain: {
        value: "PP",
        status: "error",
        panelState: "editable",
        invalidValue: "PP",
        cellCount: 4,
        holeCount: 2,
      },
      legacyCode: "Zanco",
      minDiagnostic: "OIC",
      oxidation: "Partial",
      sampleType: "Core",
      assayAu: "2.15",
      assayCu: {
        value: "xyz123",
        status: "error",
        panelState: "editable",
        invalidValue: "xyz123",
        cellCount: 3,
        holeCount: 2,
      },
      recoveryPct: "94.1",
      alteration: {
        value: "unk99",
        status: "error",
        panelState: "editable",
        invalidValue: "unk99",
        cellCount: 2,
        holeCount: 1,
      },
      geologist: "J. Rivera",
      dateLogged: "2024-03-01",
      structureCode: "F3-E",
    },
  },
  {
    id: "row-4",
    cells: {
      holeNumber: "RJ220",
      from: "107.0",
      to: "120.0",
      length: {
        value: "13.222",
        status: "error",
        panelState: "editable",
        invalidValue: "13.222",
        cellCount: 3,
        holeCount: 1,
      },
      rcDd: "",
      lithoDomain: {
        value: "PP",
        status: "error",
        panelState: "editable",
        invalidValue: "PP",
        cellCount: 4,
        holeCount: 2,
      },
      legacyCode: "Zanco",
      minDiagnostic: "OIC",
      oxidation: "",
      sampleType: "Core",
      assayAu: "0.55",
      assayCu: "0.09",
      recoveryPct: "91.8",
      alteration: "Silicic",
      geologist: "M. Chen",
      dateLogged: "2024-03-14",
      structureCode: "F1-NE",
    },
  },
  {
    id: "row-5",
    cells: {
      holeNumber: "RJ221",
      from: "0.0",
      to: "45.0",
      length: "45.0",
      rcDd: "RC",
      lithoDomain: "Sap",
      legacyCode: "Bnd",
      minDiagnostic: "BND",
      oxidation: "Fresh",
      sampleType: "RC",
      assayAu: "0.12",
      assayCu: "0.04",
      recoveryPct: "99.0",
      alteration: "Propylitic",
      geologist: "A. Okonkwo",
      dateLogged: "2024-01-09",
      structureCode: "F4-SW",
    },
  },
  {
    id: "row-6",
    cells: {
      holeNumber: "RJ221",
      from: "45.0",
      to: "90.0",
      length: "45.0",
      rcDd: "RC",
      lithoDomain: {
        value: "PP",
        status: "approved",
        panelState: "approved",
        invalidValue: "PP",
        cellCount: 1,
        holeCount: 1,
        initialStagedValue: "bnd",
      },
      legacyCode: "Lst",
      minDiagnostic: "LST",
      oxidation: "Oxidized",
      sampleType: "RC",
      assayAu: "3.44",
      assayCu: "0.67",
      recoveryPct: "97.3",
      alteration: {
        value: "Silicic",
        status: "approved",
        panelState: "approved",
        invalidValue: "Silicic",
        cellCount: 1,
        holeCount: 1,
        initialStagedValue: "lst-c",
      },
      geologist: "J. Rivera",
      dateLogged: "2024-01-11",
      structureCode: "F2-NW",
    },
  },
  ...Array.from({ length: 11 }, (_, index) => createRepeatRow(index + 7)),
];
